---
- name: Check for the specific loopback route on all routers
  hosts: arista_ceos
  gather_facts: no

  tasks:
    - name: Check if 11.11.11.11/32 route exists on all routers
      arista.eos.command:
        commands:
          - show ip route 11.11.11.11
      register: specific_route

    - name: Display route details for 11.11.11.11/32
      debug:
        var: specific_route.stdout_lines