all:
  vars:
    # The generated inventory is assumed to be used from the clab host.
    # Hence no http proxy should be used. Therefore we make sure the http
    # module does not attempt using any global http proxy.
    ansible_httpapi_use_proxy: false
  children:
    arista_ceos:
      vars:
        # ansible_connection: set ansible_connection variable if required
        ansible_user: admin
        ansible_password: admin
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: arista.eos.eos
        ansible_become: true
        ansible_become_method: enable
      hosts:
        r1:
          ansible_host: 172.20.20.11
        r2:
          ansible_host: 172.20.20.12
        r3:
          ansible_host: 172.20.20.13